Tema5
UnirCs/DWFS-PER7660-2223 pull request #103
Opened 2023-05-02 00:43 UTC by JMolinaLeon

2023-05-02 18:07 UTC, UnirCs commented on 05_Tema5/Bryam_Guzman/master-dashboard/package-lock.json
Estas modificando este archivo que no es tuyo José Luis

2023-05-02 18:08 UTC, UnirCs requested changes
El ejercicio en sí está bien José Luis. pero estás modificando el archivo de otro compañero. Tienes que eliminar ese archivo de la PR

2023-05-02 22:00 UTC, JMolinaLeon commented
Se encuentra corregido

2023-05-03 19:55 UTC, UnirCs approved these changes
OK!

2023-05-03 19:55 UTC, merged