Jorge Patricio Santamaría Cherrez ejercicio del tema 5 - Cards
UnirCs/DWFS-PER7660-2223 pull request #118
Opened 2023-05-15 16:48 UTC by Patogol35

ejercicio del tema 5 - Cards

2023-05-15 17:33 UTC, UnirCs commented on 05_Tema5/Jorge_Patricio_Santamaria_Cherrez_Ejercicio_Tema5_Cards/master_dashboard_Ejercicio_5_Jorge_Patricio_Santamaría_Cherrez/src/App.js
> +      <Card/>
Realmente, para hacer uso de la orientación a componentes, una "Card" debería tener información de 1 asignatura. Y no tener 1 única para todas.

2023-05-15 17:34 UTC, UnirCs requested changes
Queremos hacer uso de la orientación a componentes Jorge Patricio.
Refactoriza un poco el código para tener N "Card" donde cada una reciba como parámetro los datos que necesite para mostrar el contenido.

Con cualquier duda, no dudes en contactarme.

2023-05-16 06:26 UTC, UnirCs approved these changes
ahora sí, muy bien!

2023-05-16 06:26 UTC, merged

2023-05-16 16:40 UTC, Patogol35 commented
Gracias estimado ingeniero Jesus que tenga una gran semana
________________________________
De: UNIR - Computer Science ***@***.***>
Enviado: martes, 16 de mayo de 2023 0:26
Para: UnirCs/DWFS-PER7660-2223 ***@***.***>
Cc: Patogol35 ***@***.***>; Author ***@***.***>
Asunto: Re: [UnirCs/DWFS-PER7660-2223] Jorge Patricio Santamaría Cherrez ejercicio del tema 5 - Cards (PR #118)


@UnirCs approved this pull request.

ahora sí, muy bien!

—
Reply to this email directly, view it on GitHub<https://github.com/UnirCs/DWFS-PER7660-2223/pull/118#pullrequestreview-1427810266>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A6VTLN32ZNAIJTHXEPLYX73XGMM2DANCNFSM6AAAAAAYCOWEDA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>