Ejercicio tema 6
UnirCs/DWFS-PER7660-2223 pull request #127
Opened 2023-05-27 19:24 UTC by javierpina990

2023-05-28 00:36 UTC, UnirCs commented on 06_Tema6/JavierPinaLancho/T6_E1.md
> +| POST          | /partidas/{id_partida}/jugadores/{id_jugador}/barcos/{id_barco}  | JSON {"coordinate": array, "board": board_1/board_2}  | 200 Ok, 404 No found, 500 Error |
Un post no puede pedir un id de barco. Precisamente es el POST el que devuelve ese ID.
Sería POST /partidas/{id_partida}/jugadores/{id_jugador}/barcos

2023-05-28 00:37 UTC, UnirCs commented on 06_Tema6/JavierPinaLancho/T6_E1.md
> +| DELETE        | /partidas/{id_partida}   | JSON {"id_gamers": array, "status": desactive} | 202 Borrado, 404 No found, 500 Error |
Si usas PATCH para iniciar, deberías usar PATCH para finalizar. Tal como lo tienes declarado arriba, solo cambiaria el status. No tiene sentido usar delete y eliminar la partida

2023-05-28 00:38 UTC, UnirCs commented on 06_Tema6/JavierPinaLancho/T6_E1.md
> +| PUT           | /jugador                | JSON {"name": string}                      | 201 Creado, 400 Bad Request, 500 Error |
Esto tiene que ser un POST. con POST creamos cosas. con PUT las actualizamos

2023-05-28 00:38 UTC, UnirCs commented on 06_Tema6/JavierPinaLancho/T6_E1.md
A excepción de los pequeños detalles que te he comentado, está mucho mejor que antes Javier, buen trabajo

2023-05-28 00:41 UTC, UnirCs commented on 06_Tema6/JavierPinaLancho/T6_E2.md
El de la flota que es más difícil lo tienes mucho mejor que este!!!

que es calculator_basic y calculator_complex ??? son conceptos un poco raros no?

te doy una pista, piensa de alguna de estas dos formas:

- tengo un unico tipo de recurso, operaciones, por lo que mis endpoints seran [VERBO] /operaciones . El body variara en funcion del tipo de operacion.
- tengo varios tipos de recursos, sumas, restas, divisiones... tendré [VERBO] /sumas, [VERBO] /restas etc.

Sigue el mismo razonamiento que has seguido para el ejercicio de la flota, ahí los tiros van bien.

2023-05-28 00:42 UTC, UnirCs requested changes
Revisa los comentarios Javier, pero en general, mejor que antes :D
Con cualquier duda preguntame
ANIMO!

2023-05-28 08:07 UTC, javierpina990 commented on 06_Tema6/JavierPinaLancho/T6_E1.md
gracias, hago los cambios. Que ya estoy pillando la dinamica de los End Points

2023-05-28 08:10 UTC, javierpina990 commented
Cambios realizados

2023-05-28 19:07 UTC, UnirCs commented on 06_Tema6/JavierPinaLancho/T6_E2.md
> +| POST          | /multiplicar    | JSON {"type_eq": mult, "operators_1": double, "operators_2": double} | 200 OK JSON {"result": double , "id_operacion": string}, 404 NF |
sin uso de verbos!! no multiplicar sino multiplicaciones, lo mismo con dividir

2023-05-28 19:07 UTC, UnirCs requested changes
Ya casi Javier, solo te han fallado 2 en la calculadora!

2023-05-29 05:04 UTC, javierpina990 commented on 06_Tema6/JavierPinaLancho/T6_E2.md
> +| POST          | /multiplicar    | JSON {"type_eq": mult, "operators_1": double, "operators_2": double} | 200 OK JSON {"result": double , "id_operacion": string}, 404 NF |
hecho

2023-05-30 17:14 UTC, UnirCs approved these changes
Ok!

2023-05-30 17:14 UTC, merged