The activities of topic 6 have been developed
UnirCs/DWFS-PER7660-2223 pull request #129
Opened 2023-06-04 17:23 UTC by jesusagudo25

2023-06-06 21:16 UTC, UnirCs commented on 06_Tema6/JesusAgudoMurillo/calculadora/API.md
> +| Método HTTP  | URI | Body | Respuesta |
OK, pero los recursos en las URIs siempre en plural... /sumas, /restas, /raices etc

2023-06-06 21:20 UTC, UnirCs commented on 06_Tema6/JesusAgudoMurillo/hundir_la_flota/API.md
> +| PUT  | /partida/:id | { estado: string } | 200 OK, 404 NF
Esto es una modificacion parcial, por tanto PATCH

2023-06-06 21:21 UTC, UnirCs commented on 06_Tema6/JesusAgudoMurillo/hundir_la_flota/API.md
> +## API REST
En general ok, salvo lo de singular vs plural que comentaba en el otro ejercicio.

2023-06-06 21:21 UTC, UnirCs requested changes
Revisa los comentarios Jesús.
En general buen trabajo!

2023-06-07 00:14 UTC, jesusagudo25 commented
Gracias por los comentarios.

2023-06-07 00:29 UTC, jesusagudo25 commented
He aplicado las correciones.

2023-06-07 06:48 UTC, merged