T8 finalizado
UnirCs/DWFS-PER7660-2223 pull request #130
Opened 2023-06-15 04:28 UTC by bguzman012

2023-06-18 15:59 UTC, UnirCs commented on 08_Tema8/Bryam_Guzman/operaciones/src/main/java/unir/guzman/operaciones/OperacionesApplication.java
La implementación de la calculadora, OK! ;)

2023-06-18 16:00 UTC, UnirCs commented on 08_Tema8/Bryam_Guzman/battleship/ms-battleship-accounts/src/main/java/unir/spring/msbattleshipaccounts/MsBattleshipAccountsApplication.java
OK este micro

2023-06-18 16:04 UTC, UnirCs commented on 08_Tema8/Bryam_Guzman/battleship/ms-battleship-operations/src/main/java/unir/spring/msbattleshipoperations/service/BarcosServiceImpl.java
En esta capa de servicio falta toda la validación de las coordenadas del barco.
Hay que tener en cuenta todas las reglas que se indican en el PDF del tema 6!

2023-06-18 16:04 UTC, UnirCs requested changes
Falta la implementación de las validaciones a la hora de introducir barcos
Revisa un comentario que deje por el foro de la asignatura.

2023-06-20 03:46 UTC, bguzman012 commented on 08_Tema8/Bryam_Guzman/battleship/ms-battleship-operations/src/main/java/unir/spring/msbattleshipoperations/service/BarcosServiceImpl.java
Profesor, he agregado las validaciones solicitadas, le agradezco por las observaciones.

2023-06-20 12:11 UTC, UnirCs commented on 08_Tema8/Bryam_Guzman/battleship/ms-battleship-operations/src/main/java/unir/spring/msbattleshipoperations/service/DisparosServiceImpl.java
Aqui faltaria alguna logica tambien para indicarle al usuario si el disparo dió a un barco o no, o si lo hundió completamente.

Por otro lado, si un disparto hunde el último barco de un jugador, la partida termina y uno de los jugadores gana.

Hay que implementar eso

2023-06-20 12:12 UTC, UnirCs requested changes
OK la parte de la validacion de barcos Bryam, faltaría algo similar en la parte de disparos para que en algún momento la partida termine! si no jugamos todo el rato :)

Muy buen trabajo, solo te falta eso, disculpa por no habértelo dicho la otra vez, no caí.

2023-06-21 05:07 UTC, bguzman012 commented on 08_Tema8/Bryam_Guzman/battleship/ms-battleship-operations/src/main/java/unir/spring/msbattleshipoperations/service/DisparosServiceImpl.java
Las validaciones del disparo han sido agregadas; muchas gracias  por la retroalimentación constante.

2023-06-23 19:12 UTC, UnirCs commented
OK Bryam, buen trabajo :)
Ánimo con el examen

2023-06-23 19:13 UTC, UnirCs approved these changes

2023-06-23 19:13 UTC, merged