API Rest T8 realizadas.
UnirCs/DWFS-PER7660-2223 pull request #135
Opened 2023-06-27 21:11 UTC by lolacmartinlopez

-Tengo dudas en sí he realizado adecuadamente las API´s en base al rediseño que he realizado. 
-He incluido los ficheros ".md" para que quede claro que endpoints se ha implementado.

2023-06-30 12:23 UTC, UnirCs commented on 06_Tema6/Lola_Cristina_Martin_Lopez/hundir_la_flota/flota.md
> +| POST	|/partida	|{"jugador_1": "id_jugador_1", "jugador_2": "id_jugador_2"}	|201 Created, 400 Bad Request
Esto lo tenías bien!!! /partidas, siempre plural

2023-06-30 12:24 UTC, UnirCs commented on 08_Tema8/00_RESOURCES/T8_E1.md
No borres mis archivos :(

2023-06-30 12:24 UTC, UnirCs commented on 08_Tema8/00_RESOURCES/T8_E2.md
No borres mis archivos :(

2023-06-30 12:27 UTC, UnirCs commented on 08_Tema8/Lola_Cristina_Martin_Lopez/calculadora/ms-calculadora/src/main/java/controller/OperacionController.java
> +	@Qualifier("Servicio player controller")
Se suele usar Qualifier cuando hay varios beans de un mismo tipo (tpicamente por el uso de interfaces) para poder indicar cual queremos usar. No está mal que lo uses, eso si, en este caso donde solo hay una implementacion de la interfaz, aporta poco.

Por otro lado, te recomiendo que hagas referencia a la interfaz y no a la clase concreta que la implementa (inyeccion por interfaz)

2023-06-30 12:28 UTC, UnirCs commented on 08_Tema8/Lola_Cristina_Martin_Lopez/calculadora/calculadora.md
OK esta implementacion, con las consideraciones que comento en alguno de los archivos

2023-06-30 12:33 UTC, UnirCs commented on 08_Tema8/Lola_Cristina_Martin_Lopez/flota/ms-operations/src/main/java/com/example/T8/ms/controller/ShipController.java
> +	@GetMapping("/{jugador_id}/barcos")
conceptualmente, a nivel api, los barcos tienen que estar asociados a una partida. Dentro de la partida pueden estar en la raiz de la partida (ser un atributo de la partida) o asociados al jugador, como lo tienes.
Pero deben estar dentro de una partida si o si, no tiene mucho sentido que estén "sueltos".
Cuando los cree, los creare dentro del contexto de una partida y para un jugador concreto por lo que la api debe reflejr eso

2023-06-30 12:33 UTC, UnirCs commented on 08_Tema8/Lola_Cristina_Martin_Lopez/flota/ms-operations/src/main/java/com/example/T8/ms/controller/ShootController.java
aqui esta la chicha :)

2023-06-30 12:35 UTC, UnirCs commented on 08_Tema8/Lola_Cristina_Martin_Lopez/flota/ms-operations/src/main/java/com/example/T8/ms/controller/ShipController.java
> +
en linea con el comentario de abajo, aqui puedes poner un @RequestMapping("/partidas"). Eso hara que todos los endpoints que declares en el controlador sean siempre /partidas + lo que definas en cada metodo. Es como sacar factor comun

2023-06-30 12:36 UTC, UnirCs requested changes
Hola Lola, revisa los comentarios que te he dejado.
La calculadora OK, de la flota revisa algún detalle a nivel API y luego por otro lado, completa la implementacion con los disparos si te da tiempo. Si tienes dudas dime por aqui o por el foro.

2023-07-05 07:21 UTC, lolacmartinlopez commented on 08_Tema8/Lola_Cristina_Martin_Lopez/calculadora/ms-calculadora/src/main/java/controller/OperacionController.java
> +	@Qualifier("Servicio player controller")
Podría ponerme un ejemplo de esto? Dado que en los apuntes encuentro inyección por clase y por atributo.

2023-07-05 07:23 UTC, lolacmartinlopez commented on 08_Tema8/Lola_Cristina_Martin_Lopez/flota/ms-operations/src/main/java/com/example/T8/ms/controller/ShipController.java
> +	@GetMapping("/{jugador_id}/barcos")
Sería algo así: @GetMapping("/partidas/{partida_id}/{jugador_id}/barcos")?

2023-07-05 07:23 UTC, lolacmartinlopez commented on 08_Tema8/Lola_Cristina_Martin_Lopez/flota/ms-operations/src/main/java/com/example/T8/ms/controller/ShootController.java
esto no se muy bien como implementarlo, en base al diseño de API que he realizado.

2023-07-05 07:25 UTC, lolacmartinlopez commented on 08_Tema8/Lola_Cristina_Martin_Lopez/flota/ms-operations/src/main/java/com/example/T8/ms/controller/ShipController.java
> +
En este caso, habría que hacer 1 por cada método que se desee? 

Ejemplo: 

@RequestMapping(
  value = "/ex/foos", 
  method = GET, 
  headers = "Accept=application/json")
@ResponseBody
public String getFoosAsJsonFromBrowser() {
    return "Get some Foos with Header Old";
}

@RequestMapping(
  value = "/ex/foos", 
  method = POST, 
  headers = "Accept=application/json")
@ResponseBody
public String getFoosAsJsonFromBrowser() {
    return "Post some Foos with Header Old";
}

2023-07-05 10:57 UTC, UnirCs commented on 08_Tema8/Lola_Cristina_Martin_Lopez/calculadora/ms-calculadora/src/main/java/controller/OperacionController.java
> +	@Qualifier("Servicio player controller")
Tienes razón Lola, no tengo ejemplos de eso. Me lo apunto :) 

Echa un ojo a este artículo: https://www.baeldung.com/spring-profiles

Imagina que tengo una app web de compras de lo que sea y tengo formas de pago diferentes en españa y en francia. Podría tener sentido tener dos fachadas distintas para cada proveedor en función del país, SpainPaymentFacade y FrancePaymentFacade. Aún con sus diferencias a nivel de implementación, podrían extender de una interfaz PaymentFacade con un método pay() que será reimplementado en cada clase concreta en función de las especificidades de cada país.

por tanto imagina mi interfaz
public inteface PaymentFacade {
void pay(...);
}

y mis clases concretas

@Profile("es")
public class SpainPaymentFacade implements PaymentFacade {
@Override
public void pay(...) {
//lo que sea para ES
}
}

@Profile("fr")
public class FrancePaymentFacade implements PaymentFacade {
@Override
public void pay(...) {
//lo que sea para FR
}
}

En mi capa de servicio yo tendré un @autowired de PaymentFacade, de forma que cuando el código se arranque con perfil "es", esa variable será de tipo SpainPaymentFacade. Igual para el caso de fr. Eso es la inyección por interfaz

2023-07-05 10:58 UTC, UnirCs commented on 08_Tema8/Lola_Cristina_Martin_Lopez/flota/ms-operations/src/main/java/com/example/T8/ms/controller/ShipController.java
> +	@GetMapping("/{jugador_id}/barcos")
Sí, tendría bastante sentido

2023-07-05 11:02 UTC, UnirCs commented on 08_Tema8/Lola_Cristina_Martin_Lopez/flota/ms-operations/src/main/java/com/example/T8/ms/controller/ShipController.java
> +
No no, únicamente la notación request mapping con la URI, y a nivel de clase, así:

```
package com.student.controllers;

// Importing required classes
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

// Annotations
@Controller
@RequestMapping("/boys") < ---------- Esto, hace que todos los endpoints declarados en la clase comiencen siempre por "/boys".
// Class
public class DemoController {

	@ResponseBody
	@RequestMapping("/hello")

	// Method
	public String helloWorld()
	{
		return "Hello World!";
	}

	// Annotation
	@ResponseBody
	@RequestMapping("/geeksforgeeks")

	// Method
	public String welcomeGfgMessage()
	{
		return "Welcome to GeeksforGeeks";
	}
}
```

Obtenido de: https://www.geeksforgeeks.org/spring-requestmapping-annotation-with-example/

2023-07-05 11:09 UTC, UnirCs commented on 08_Tema8/Lola_Cristina_Martin_Lopez/flota/ms-operations/src/main/java/com/example/T8/ms/controller/ShootController.java
Revisaste el comentario que te dejé por el campus virtual respecto a esto, qué dudas te surgen?

2023-07-06 06:11 UTC, lolacmartinlopez commented on 08_Tema8/Lola_Cristina_Martin_Lopez/flota/ms-operations/src/main/java/com/example/T8/ms/controller/ShipController.java
> +
Vale de acuerdo, lo tendré en cuenta para la próxima, gracias!

2023-07-06 06:12 UTC, lolacmartinlopez commented on 08_Tema8/Lola_Cristina_Martin_Lopez/flota/ms-operations/src/main/java/com/example/T8/ms/controller/ShootController.java
Realizado en base a sus recomendaciones.

2023-07-06 06:12 UTC, lolacmartinlopez commented on 08_Tema8/Lola_Cristina_Martin_Lopez/calculadora/ms-calculadora/src/main/java/controller/OperacionController.java
> +	@Qualifier("Servicio player controller")
Intentaré implementarlo en la próxima iteración. Gracias por la explicación!

2023-07-06 08:23 UTC, UnirCs approved these changes
Te dejo aprobada y mergeada la PR, a falta del comentario que he puesto, pero en general para una version inicial está bien ;) buen trabajo

2023-07-06 08:24 UTC, merged

2023-07-06 08:27 UTC, lolacmartinlopez commented on 08_Tema8/Lola_Cristina_Martin_Lopez/flota/ms-operations/src/main/java/com/example/T8/ms/controller/ShootController.java
> +	public ResponseEntity<Shoot> partialModifyShoot(@RequestBody PatchShootRequest request, @PathVariable int id_partida){
Si, cierto, se necesitaría para que dentro del servicio Shoot, se buscará en el repositorio para una partida en concreto, el jugador con ese id_jugador y encontrar que matriz de posiciones tiene en ese instante dado. Lo corrijo en mi local, aunque también a la implementación de la función en el servicio debería de echarle otro vistazo, seguramente, tras los exámenes. 

Muchas gracias por todo!