Tarea 1 CV y Boostrap
UnirCs/DWFS-PER7660-2223 pull request #41
Opened 2023-03-30 08:00 UTC by JMolinaLeon

2023-03-30 10:30 UTC, UnirCs commented on 01_Tema1/jose-luis-molina-leon/cv/cv.html
> +                    <div style="width: 400px; text-align: justify;">
No debes usar estilos inline salvo que el caso esté justificado. En este caso no lo está, podrías haber usado una clase css perfectamente

2023-03-30 10:31 UTC, UnirCs commented on 01_Tema1/jose-luis-molina-leon/cv/cv.html
> +                        <img src="./img/ri_3.png" alt="Foto"  style="width: 15px;">
Uso de estilo inline innecesario

2023-03-30 10:32 UTC, UnirCs requested changes
Un estilo inline se aplica cuando no es posible ajustarse al modelo de clases css que se ha definido.
En tu caso, se pueden usar clases css perfectamente.

https://worldofdev.info/6-reasons-why-you-shouldnt-style-inline/

2023-03-31 00:54 UTC, JMolinaLeon commented on 01_Tema1/jose-luis-molina-leon/cv/cv.html
> +                        <img src="./img/ri_3.png" alt="Foto"  style="width: 15px;">
Buenas noches, se realizaron los cambios.

2023-03-31 00:54 UTC, JMolinaLeon commented on 01_Tema1/jose-luis-molina-leon/cv/cv.html
> +                    <div style="width: 400px; text-align: justify;">
Buenas noches, se realizaron los cambios.

2023-03-31 06:52 UTC, UnirCs approved these changes
Ok!

2023-03-31 06:52 UTC, merged