Create CV
UnirCs/DWFS-PER7660-2223 pull request #54
Opened 2023-04-04 23:14 UTC by Jasson-x

2023-04-05 06:58 UTC, UnirCs commented on 01_Tema1/Jasson Espitia/CV
Archivo sin extensión .html

2023-04-05 06:58 UTC, UnirCs commented on 01_Tema1/Jasson Espitia/Form
Archivo sin extensión .html

2023-04-05 06:59 UTC, UnirCs requested changes
Falta todo el código CSS

2023-04-08 17:41 UTC, Jasson-x commented on 01_Tema1/Jasson Espitia/Form
> Archivo sin extension .html

2023-04-13 07:33 UTC, UnirCs approved these changes
ok

2023-04-13 07:33 UTC, merged