Agregados ejercicios 1 y 2 del tema 1, CV y Pasarela de pago
UnirCs/DWFS-PER7660-2223 pull request #74
Opened 2023-04-14 22:18 UTC by jlsalazarm

2023-04-15 21:46 UTC, UnirCs requested changes
Sustituye los estilos inline que tengas por referencias a clases CSS ya que no está justificado el uso que haces de estos inline

https://worldofdev.info/6-reasons-why-you-shouldnt-style-inline/

2023-04-15 21:46 UTC, UnirCs commented on 01_Tema1/Jose_Luis_Salazar/T1_E2/Index.html
> +                <p class="ps-2 name" style="margin-bottom: 0px;">Cart</p>
Uso de estilos inline injustificado

2023-05-02 04:00 UTC, jlsalazarm commented
Hola, ya he realizado la corrección, quedo atento.

2023-05-02 18:09 UTC, UnirCs approved these changes
OK!

2023-05-02 18:09 UTC, merged